package sifive.fpgashells.ip.xilinx.ku5pmig

import chisel3._
import chisel3.experimental.{Analog, ExtModule, attach}
import freechips.rocketchip.util.ElaborationArtefacts
import org.chipsalliance.cde.config.Parameters

/** Physical interface for the two MT40A256M16GE-075E devices on XCKU5P_DEMO. */
class Ku5pMIGDDRPads extends Bundle {
  // Field ordering is kept stable because Ku5pShell assigns package pins by field.
  val ck_c: UInt       = Output(UInt(1.W))
  val ck_t: UInt       = Output(UInt(1.W))
  val cke: UInt        = Output(UInt(1.W))
  val cs_n: UInt       = Output(UInt(1.W))
  val act_n: Bool      = Output(Bool())
  val odt: UInt        = Output(UInt(1.W))
  val adr: UInt        = Output(UInt(17.W))
  val ba: UInt         = Output(UInt(2.W))
  val bg: UInt         = Output(UInt(1.W))
  val reset_n: Bool    = Output(Bool())
  val dqs_c: Analog    = Analog(4.W)
  val dqs_t: Analog    = Analog(4.W)
  val dq: Analog       = Analog(32.W)
  val dm_dbi_n: Analog = Analog(4.W)
}

object Ku5pMIGDDRPads {
  /** Connect one DDR pad bundle explicitly so output directions remain clear
    * when the bundle passes through module and BundleBridge boundaries.
    */
  def connect(sink: Ku5pMIGDDRPads, source: Ku5pMIGDDRPads): Unit = {
    sink.ck_c := source.ck_c
    sink.ck_t := source.ck_t
    sink.cke := source.cke
    sink.cs_n := source.cs_n
    sink.act_n := source.act_n
    sink.odt := source.odt
    sink.adr := source.adr
    sink.ba := source.ba
    sink.bg := source.bg
    sink.reset_n := source.reset_n
    attach(sink.dqs_c, source.dqs_c)
    attach(sink.dqs_t, source.dqs_t)
    attach(sink.dq, source.dq)
    attach(sink.dm_dbi_n, source.dm_dbi_n)
  }
}

/**
  * DDR4 controller generated by Vivado.
  *
  * The board provides a 100 MHz differential clock on T24/U24.  The overlay
  * buffers that clock, so the MIG is configured for a no-buffer system clock.
  * DDR is deliberately run at 800 MT/s (1250 ps) for bring-up margin.
  */
class ku5pmig(implicit val p: Parameters) extends ExtModule {
  val c0_sys_clk_i: Clock            = IO(Input(Clock()))
  val sys_rst: Reset                 = IO(Input(Reset()))
  val c0_ddr4_ui_clk: Clock          = IO(Output(Clock()))
  val c0_ddr4_ui_clk_sync_rst: Reset = IO(Output(Bool()))
  val c0_init_calib_complete: Bool   = IO(Output(Bool()))

  val c0_ddr4_intf: Ku5pMIGDDRPads = IO(new Ku5pMIGDDRPads).suggestName("c0_ddr4")

  val c0_ddr4_aresetn: Bool = IO(Input(Bool()))

  val c0_ddr4_s_axi_awid: UInt    = IO(Input(UInt(4.W)))
  val c0_ddr4_s_axi_awaddr: UInt  = IO(Input(UInt(30.W)))
  val c0_ddr4_s_axi_awlen: UInt   = IO(Input(UInt(8.W)))
  val c0_ddr4_s_axi_awsize: UInt  = IO(Input(UInt(3.W)))
  val c0_ddr4_s_axi_awburst: UInt = IO(Input(UInt(2.W)))
  val c0_ddr4_s_axi_awlock: UInt  = IO(Input(UInt(1.W)))
  val c0_ddr4_s_axi_awcache: UInt = IO(Input(UInt(4.W)))
  val c0_ddr4_s_axi_awprot: UInt  = IO(Input(UInt(3.W)))
  val c0_ddr4_s_axi_awqos: UInt   = IO(Input(UInt(4.W)))
  val c0_ddr4_s_axi_awvalid: Bool = IO(Input(Bool()))
  val c0_ddr4_s_axi_awready: Bool = IO(Output(Bool()))

  val c0_ddr4_s_axi_wdata: UInt  = IO(Input(UInt(64.W)))
  val c0_ddr4_s_axi_wstrb: UInt  = IO(Input(UInt(8.W)))
  val c0_ddr4_s_axi_wlast: Bool  = IO(Input(Bool()))
  val c0_ddr4_s_axi_wvalid: Bool = IO(Input(Bool()))
  val c0_ddr4_s_axi_wready: Bool = IO(Output(Bool()))

  val c0_ddr4_s_axi_bready: Bool = IO(Input(Bool()))
  val c0_ddr4_s_axi_bvalid: Bool = IO(Output(Bool()))
  val c0_ddr4_s_axi_bid: UInt    = IO(Output(UInt(4.W)))
  val c0_ddr4_s_axi_bresp: UInt  = IO(Output(UInt(2.W)))

  val c0_ddr4_s_axi_arid: UInt    = IO(Input(UInt(4.W)))
  val c0_ddr4_s_axi_araddr: UInt  = IO(Input(UInt(30.W)))
  val c0_ddr4_s_axi_arlen: UInt   = IO(Input(UInt(8.W)))
  val c0_ddr4_s_axi_arsize: UInt  = IO(Input(UInt(3.W)))
  val c0_ddr4_s_axi_arburst: UInt = IO(Input(UInt(2.W)))
  val c0_ddr4_s_axi_arlock: UInt  = IO(Input(UInt(1.W)))
  val c0_ddr4_s_axi_arcache: UInt = IO(Input(UInt(4.W)))
  val c0_ddr4_s_axi_arprot: UInt  = IO(Input(UInt(3.W)))
  val c0_ddr4_s_axi_arqos: UInt   = IO(Input(UInt(4.W)))
  val c0_ddr4_s_axi_arvalid: Bool = IO(Input(Bool()))
  val c0_ddr4_s_axi_arready: Bool = IO(Output(Bool()))

  val c0_ddr4_s_axi_rready: Bool = IO(Input(Bool()))
  val c0_ddr4_s_axi_rvalid: Bool = IO(Output(Bool()))
  val c0_ddr4_s_axi_rdata: UInt  = IO(Output(UInt(64.W)))
  val c0_ddr4_s_axi_rresp: UInt  = IO(Output(UInt(2.W)))
  val c0_ddr4_s_axi_rid: UInt    = IO(Output(UInt(4.W)))
  val c0_ddr4_s_axi_rlast: Bool  = IO(Output(Bool()))

  ElaborationArtefacts.add(
    "ku5pmig.vivado.tcl",
    """create_ip -vendor xilinx.com -library ip -version 2.2 -name ddr4 -module_name ku5pmig -dir $ipdir -force
      |set_property -dict [list \
      |  CONFIG.AL_SEL                               {0} \
      |  CONFIG.C0.ADDR_WIDTH                        {17} \
      |  CONFIG.C0.BANK_GROUP_WIDTH                  {1} \
      |  CONFIG.C0.CKE_WIDTH                         {1} \
      |  CONFIG.C0.CK_WIDTH                          {1} \
      |  CONFIG.C0.CS_WIDTH                          {1} \
      |  CONFIG.C0.ControllerType                    {DDR4_SDRAM} \
      |  CONFIG.C0.DDR4_AxiAddressWidth              {30} \
      |  CONFIG.C0.DDR4_AxiArbitrationScheme         {RD_PRI_REG} \
      |  CONFIG.C0.DDR4_AxiDataWidth                 {64} \
      |  CONFIG.C0.DDR4_AxiIDWidth                   {4} \
      |  CONFIG.C0.DDR4_AxiNarrowBurst               {false} \
      |  CONFIG.C0.DDR4_AxiSelection                 {true} \
      |  CONFIG.C0.DDR4_BurstLength                  {8} \
      |  CONFIG.C0.DDR4_BurstType                    {Sequential} \
      |  CONFIG.C0.DDR4_CLKFBOUT_MULT                {10} \
      |  CONFIG.C0.DDR4_CLKOUT0_DIVIDE               {5} \
      |  CONFIG.C0.DDR4_Capacity                     {512} \
      |  CONFIG.C0.DDR4_CasLatency                   {11} \
      |  CONFIG.C0.DDR4_CasWriteLatency              {9} \
      |  CONFIG.C0.DDR4_ChipSelect                   {true} \
      |  CONFIG.C0.DDR4_DIVCLK_DIVIDE                {1} \
      |  CONFIG.C0.DDR4_DataMask                     {DM_NO_DBI} \
      |  CONFIG.C0.DDR4_DataWidth                    {32} \
      |  CONFIG.C0.DDR4_Ecc                          {false} \
      |  CONFIG.C0.DDR4_InputClockPeriod             {10000} \
      |  CONFIG.C0.DDR4_Mem_Add_Map                  {ROW_COLUMN_BANK} \
      |  CONFIG.C0.DDR4_MemoryPart                   {MT40A256M16GE-075E} \
      |  CONFIG.C0.DDR4_MemoryType                   {Components} \
      |  CONFIG.C0.DDR4_MemoryVoltage                {1.2V} \
      |  CONFIG.C0.DDR4_OnDieTermination             {RZQ/6} \
      |  CONFIG.C0.DDR4_Ordering                     {Normal} \
      |  CONFIG.C0.DDR4_OutputDriverImpedenceControl {RZQ/7} \
      |  CONFIG.C0.DDR4_PhyClockRatio                {4:1} \
      |  CONFIG.C0.DDR4_Slot                         {Single} \
      |  CONFIG.C0.DDR4_Specify_MandD                {true} \
      |  CONFIG.C0.DDR4_TimePeriod                   {1250} \
      |  CONFIG.C0.LR_WIDTH                          {1} \
      |  CONFIG.C0.ODT_WIDTH                         {1} \
      |  CONFIG.C0.StackHeight                       {1} \
      |  CONFIG.C0_CLOCK_BOARD_INTERFACE             {Custom} \
      |  CONFIG.C0_DDR4_BOARD_INTERFACE              {Custom} \
      |  CONFIG.DCI_Cascade                          {false} \
      |  CONFIG.DIFF_TERM_SYSCLK                     {false} \
      |  CONFIG.Debug_Signal                         {Disable} \
      |  CONFIG.Default_Bank_Selections              {false} \
      |  CONFIG.Enable_SysPorts                      {true} \
      |  CONFIG.IS_FROM_PHY                          {1} \
      |  CONFIG.No_Controller                        {1} \
      |  CONFIG.PING_PONG_PHY                        {1} \
      |  CONFIG.Phy_Only                             {Complete_Memory_Controller} \
      |  CONFIG.RESET_BOARD_INTERFACE                {Custom} \
      |  CONFIG.Reference_Clock                      {Differential} \
      |  CONFIG.System_Clock                         {No_Buffer} \
      |] [get_ips ku5pmig]
      |""".stripMargin
  )
}
